theme = "catppuccin-mocha"

[editor]
cursorline = true
color-modes = true

[editor.gutters]
layout = ["diff", "diagnostics", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"C-/" = "@%s"
"C-." = "@<A-.>"

[keys.normal.space]
space = "command_palette"
d = ":buffer-close"
w = { d = "wclose" }

[keys.select]
o = "flip_selections"
