theme = "catppuccin-mocha"

[editor]
cursorline = true
color-modes = true
# clipboard-provider = "termcode" # wasn't working for pasting on MACOS

[editor.gutters]
layout = ["diff", "diagnostics"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"C-/" = "@%s"
"C-." = "@<A-.>"
tab = "expand_selection"
"S-tab" = "shrink_selection"
H = "select_prev_sibling"
L = "select_next_sibling"
"C-y" = "@\"+y"
"S-c" = "@t<ret>c"
"S-d" = "@t<ret>d"
"S-y" = "@t<ret>y"

[keys.normal.space]
space = "command_palette"
tab = "goto_last_accessed_file"
d = ":buffer-close"
w = { d = "wclose" }
"=" = ":format"
q = ":wqa"

[keys.select]
"C-y" = "@\"+y"
# o = "flip_selections" # maybe just get used to the alt-; binding since it works in normal mode too
