add_newline = false

[character]
symbol = "ğŸ" # â¯
# error_symbol = "âŒ"
use_symbol_for_status = true

[directory]
style = "bold white"

[line_break]
disabled = true

[package]
disabled = true
[rust]
disabled = true
[python]
disabled = true
[java]
disabled = true
[ruby]
disabled = true
[nodejs]
disabled = true

[cmd_duration]
prefix = ""

[git_branch]
symbol = "ï„¦ " # ğŸŒ±

[git_status]
style = "purple"
conflicted = "ğŸ˜ "
ahead = "ï‚ª "
behind = " ï‚« "
show_sync_count = true
diverged = ""
stashed = " ï€œ "
untracked = " ï™ "
untracked_count.enabled = true
modified = " ïª "
modified_count.enabled = true
staged = " ï• "
staged_count.enabled = true
renamed = ""
deleted = "" # ğŸ—‘
prefix = "("
suffix = ") "

