add_newline = false

[character]
success_symbol = "ğŸ"
error_symbol = "âŒ"

[directory]
style = "bold white"

[hostname]
format = "[$hostname]($style):"

[cmd_duration]
format = "[$duration]($style) "

[git_branch]
symbol = "ï„¦ " # ğŸŒ±

[git_status]
style = "purple"
conflicted = "ğŸ˜ "
ahead = "ï‚ª $count"
behind = " ï‚« $count"
diverged = "ï‚ª $count ï‚« $count"
stashed = " ï€œ "
untracked = " ï™ $count"
modified = " ïª $count"
staged = " ï• $count"
renamed = ""
deleted = "" # ğŸ—‘

[line_break]
disabled = true
[package]
disabled = true
[rust]
disabled = true
[python]
disabled = true
[java]
disabled = true
[ruby]
disabled = true
[nodejs]
disabled = true
[gcloud]
disabled = true
[username]
disabled = true
