command_timeout = 500

format = """$username$hostname$localip$directory\
$git_branch$git_commit$git_state$git_metrics$git_status\
$container$nix_shell$env_var$custom$sudo\
$cmd_duration$jobs$battery$time$status$character"""

[character]
success_symbol = "ğŸ"
error_symbol = "ğŸ"

[status]
disabled = false
map_symbol = true
sigint_symbol = "ğŸ’€"
format = "[$symbol]($style)"

[directory]
style = "bold white"
# truncation_symbol = "â€¦/"

[hostname]
format = "[$hostname]($style):"

[cmd_duration]
format = "[$duration]($style) "

[git_branch]
symbol = "ï„¦ " # ğŸŒ±

[git_status]
style = "purple"
conflicted = "ğŸ˜ "
ahead = "ï‚ª $count"
behind = " ï‚« $count"
diverged = "ï‚ª $count ï‚« $count"
stashed = " ï€œ "
untracked = "" # for performance
# untracked = " ï™ $count"
modified = " ïª $count"
staged = " ï• $count"
renamed = ""
deleted = "îª $count"

[nix_shell]
format = '$symbol'
symbol = "â„ï¸"
